### ISSUE TITLE
Joint Contact & Plateau Surface

### ISSUE THREAD

**Issue by aaronsfox** [aaronsfox/tibial-geometry#1]
@MeghanKeast I noticed these two surface files were exported as contours in .xml files. I think that this will export the points of the extracted surface as a boundary (i.e. the outside of the surface) - when it would be easier to also have the coordinate points within the boundary as well. My suggestion would be that once you've extracted the marked triangles to a new part/surface, export these as .stl files as well. Essentially they'll be like a flat surface, almost look like a potato chip!

**Comment by MeghanKeast** [comment]
@aaronsfox ahhh okay, that makes sense. I will fix that up on Monday!

**Comment by aaronsfox** [comment]
@MeghanKeast great - I'll close this issue
