### ISSUE TITLE
Example Case 1: Generating Samples

### ISSUE THREAD

**Issue by aaronsfox** [aaronsfox/tibial-geometry#2]
@MeghanKeast

The shape models are now pushed to the repo and available to use within creating case examples. Let's use this issue to document the work and anything that pops up along the way with this coding and analysis.

There is a working directory available for this at `Examples\case1`. Put any code and files you create for this in there and document/explain the example if the README.MD file.

A starting point might be to create a checklist here that we can work through and check off what processes need to be done for this use example, e.g.

And progressively check these off through comments on this issue thread

**Comment by aaronsfox** [comment]
@MeghanKeast 

Nice work on the script for this - I simply cleaned up the code to use more consistent variable naming with other code and converted it to a function format (see 655e5a4bb3a47a110715126505943f37d0b095cf).

I realised that in its current format you could actually apply it to any of the shape models (i.e. tibia, trabecular, tibia-fibula etc.).

Perhaps give it a test spin and we can then use whatever you run through the function in the write-up for the paper (i.e. generated image from the function as a figure for example). You can see within the function code the different options you can provide and the outputs it can give (STLs, image etc.)

**Comment by MeghanKeast** [comment]
@aaronsfox 

Gave it a test spin works great - added one more step into the example for my testing to make it easier to switch between the models I am testing. 

shapeModel = tibiaFibulaShapeModel (just modify to make the name of the shape model you wish to use) 

See image for first test run.

![simulatedPopulation](https://user-images.githubusercontent.com/68574996/155065012-e7049099-2e17-4cdc-a741-39fb10730881.png)

**Comment by aaronsfox** [comment]
@MeghanKeast - great that it seems fairly self-explanatory and easy to use then. Next step is to write up a brief section on this in the paper, and that info can transfer across to the README.MD file in that case folder

**Comment by MeghanKeast** [comment]
### Case 1: Checklist

- [x] Create script

- [x] Test script 

- [ ] Manuscript write up 

- [ ] Update read me file with relevant instructions and walkthrough

**Comment by MeghanKeast** [comment]
@aaronsfox I was just creating a figure for the manuscript, The gaps between the subplots are pretty large. I tried to minimise but haven't been able to get it to work with the subplot tool. I came across a new feature for MATLAB called tiledlayout and think it might be easier to use. Only issue I foresee is people with MATLAB earlier than 2019 wont be able to use it. 

Any ideas on a solution for this? 

![tib-fib](https://user-images.githubusercontent.com/68574996/160958497-66996ea8-0975-455c-91df-01b01ab86416.png)

**Comment by aaronsfox** [comment]
@MeghanKeast I did think there was an easy way to do this but I can't find it - I'm possibly thinking of this in a Python context though. I don't think it's an issue to use a 2019 onwards function. I haven't really been keeping track of this and we'll have to report anyway what version we used and tested on. The figure creation step could also just be skipped for those without access to the feature

**Comment by MeghanKeast** [comment]
@aaronsfox 
This is the best I could do with  the tiledlayout function. 
It is much easier to manipulate, I will push the script to the repo. If you want to give it a test and make sure its still clean enough with the updates that would be great. 
![tib-fib_V2](https://user-images.githubusercontent.com/68574996/160971553-3f5c2f4a-9ddd-4416-971a-7b8467e8133b.png)
