### ISSUE TITLE
Example Case 3: Landmark Reconstruction

### ISSUE THREAD

**Issue by aaronsfox** [aaronsfox/tibial-geometry#3]
@MeghanKeast 

The mean surfaces are now available in the same folder as the shape model data. Note that you will want to register the relevant landmarks on the tibia-fibula shape model surface, as this is what we're using in the reconstruction process. Generate an identical CSV file with the landmarks on it and include it in the same folder (i.e. where the mean surface STL file is)

**Comment by aaronsfox** [comment]
@MeghanKeast 

I think you extended the anterior tibial border landmarks for the first sample, but this also needs to be done for the shape model mean!

**Comment by MeghanKeast** [comment]
@aaronsfox 

These should be updated now!

**Comment by aaronsfox** [comment]
@MeghanKeast 

Works fine now for the 75% landmark - which improves the reconstruction of the tibia towards the distal end. On the first sample I'm testing the fibula bendiness is where the max errors coming from, so I think samples that have variable fibula orientation is probably where the largest errors will present

How are the landmarks across the other surfaces going?

**Comment by MeghanKeast** [comment]
They are on this afternoons agenda.
I will push some through once I’ve done 4 or 5.

**Comment by MeghanKeast** [comment]
@aaronsfox I have pushed sample 2 through to 5 to the repo for you to use! How many samples did you want for this example?

**Comment by aaronsfox** [comment]
@MeghanKeast All of them? I think there's like 30, which could be overkill I suppose. At least 10 to start with and we can see what the error variability is. If there's a wide range of inconsistent errors then we should perhaps do more to investigate

**Comment by MeghanKeast** [comment]
@aaronsfox I have pushed the other 5 to the repo for you to use!

**Comment by aaronsfox** [comment]
@MeghanKeast thanks, planning on having a look this afternoon

**Comment by aaronsfox** [comment]
@MeghanKeast 

touching back on this - is it possible to do the landmarks for the remaining samples?

**Comment by aaronsfox** [comment]
@MeghanKeast 

can you also check the original ones you did (01-10). 07 definitely has some issues, didn't seem to run into trouble with the others but still worth a check

**Comment by MeghanKeast** [comment]
@aaronsfox It should be possible might just take me a few days with the programs I have available at the moment. 

No worries, I will have a look at it.

**Comment by MeghanKeast** [comment]
@aaronsfox I have added the landmarks for 11- 25, I am still currently working on the last 10 and hopefully will have them pushed to the repo this afternoon. I will also update tibia 07 landmarks.

**Comment by MeghanKeast** [comment]
@aaronsfox all landmark files have been pushed to the repo.

**Comment by aaronsfox** [comment]
@MeghanKeast it took me about 10 mins to write some code to covert those .pp files to .csv 👍

**Comment by aaronsfox** [comment]
@MeghanKeast you'll need to fix up C11 - it doesn't have a LM landmark

**Comment by MeghanKeast** [comment]
@aaronsfox All fixed up.
