### ISSUE TITLE
Cleaning Repo

### ISSUE THREAD

**Issue by aaronsfox** [aaronsfox/tibial-geometry#5]
@MeghanKeast 

I've started the process of cleaning up files in the repo. An FYI that I've done the README files for the case2 and case3 examples. Review these and construct the case1 README in a similar way to this. It's just really taking bits and pieces from the explanation in the paper.

**Comment by aaronsfox** [comment]
@MeghanKeast 

FYI I've cleaned up main code and the code for case2 and case3. Once you've checked the case1 code I think we can then create the branch to finalise and upload/include with paper.

**Comment by MeghanKeast** [comment]
@aaronsfox I have updated the README for Case1. I have also checked the code for case 1. 
If you want to just double check the readme file to make sure you are happy with it, I can add any changes necessary.

**Comment by aaronsfox** [comment]
@MeghanKeast 

I made some minor changes to the readme, just removing the dependencies section as this is only included in the base level readme.

I've created a new 'release' branch where I've removed anything we don't want in the dataset (the 'piloting' folder - so just make sure this isn't in anything that you download and upload to SimTK). It's located at [https://github.com/aaronsfox/tibial-geometry/tree/release](https://github.com/aaronsfox/tibial-geometry/tree/release), so this is the link we should include with the manuscript submission. You should be able to download that branch in .zip format from the 'Code' button on GitHub and then upload this to the SimTK page. When uploading, make sure to:

1. Label the download with a version number or date so that we can track any changes
2. Add the BioRxiv preprint details to the SimTK page so that people can link to and cite the paper

**Comment by MeghanKeast** [comment]
@aaronsfox SimTK page seems to be up and running. If you could have a look at it that would be great! You are also and Admin so if you think anything needs to be added you should be able to make changes.

**Comment by aaronsfox** [comment]
@MeghanKeast looks great!
